name: cv_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.9
  flutter_animate: ^4.2.0+1
  animated_background: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - image/
    - assests/
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
    - family: Cairo1
      fonts:
        - asset: fonts/Cairo-Regular1.ttf    
